---

- name: download Solr to hosts
  local_action: >
    get_url 
      url="{{solr_download_url}}"
      dest="{{solr_download_dir}}/{{solr_package}}"
  tags: download

- name: unpack Solr at control machine
  local_action: >
    unarchive
      src="{{solr_download_dir}}/{{solr_package}}"
      dest="{{solr_download_dir}}/"
  tags: unpack

- name: ensures solr.xml file is present at {{solr_installation_dir}}
  copy:
    src="solr.xml"
    dest="{{solr_installation_dir}}/"
    mode=0644

- name: ensures {{solr_lib_dir}} is present at host machine
  file:
    path="{{solr_lib_dir}}"
    state=directory
    mode=0700

- name: ensures {{solr_local_libs}} are present at {{solr_lib_dir}} at host machine
  copy:
    src="{{item}}"
    dest="{{solr_lib_dir}}/"
  with_items: solr_local_libs
  when: solr_local_libs is defined and solr_lib_dir is defined

- name: ensures solr dist and external dependencies are present at host machine
  copy:
    src="{{solr_local_lib_dir}}"
    dest="{{solr_installation_dir}}/{{solr_lib_dir}}"
  when: solr_local_lib_dir is defined

- include: jetty.yml
  when: solr_container == 'jetty'

- include: tomcat.yml
  when: solr_container == 'tomcat'
